server:
  port: 8080

logging:
  level:
    root: info
    cc.niushuai: debug
  file:
    path: ${LOG_PATH:.}
    name: @artifactId@-@version@.log
spring:
  datasource:
    url: jdbc:h2:file:./shuai-push
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: H2
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DB_INDEX:2}

# 自定义配置
push:
  sendKey: ${sendKey:}
  enableService: ${enableService:all}
  # 企业微信内部应用
  wework:
    # 企业id
    corpId: ${wxCpCorpId:}
    # 企业秘钥
    corpSecret: ${wxCpCorpSecret:}
    # 企业内部应用id
    appId: ${wxCpAppId:}
  # 微信公众号
  weixin:
    # 微信公众号id
    appid: ${wxAppId:}
    # 微信公众号秘钥
    appSecret: ${wxAppSecret:}
