version: '3'
services:
  shuai-push:
    restart: always
    image: niushuai233/shuai-push:${VERSION}
    container_name: shuai-push-${VERSION}
    ports:
      - ${EXPORT_PORT}:8080
    environment:
      LOG_PATH: ${LOG_PATH}
      sendKey: ${SEND_KEY}
      enableService: ${ENABLE_SERVICE}
      wxCpCorpId: ${WX_CP_CORP_ID}
      wxCpCorpSecret: ${WX_CP_CORP_SECRET}
      wxCpAppId: ${WX_CP_APP_ID}
      wxAppId: ${WX_APP_ID}
      wxAppSecret: ${WX_APP_SECRET}
